services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME}"
    image: localstack/localstack
    ports:
      - 4566:4566 # LocalStack Gateway
      # - 4510-4559:4510-4559 # external services port range
    env_file:
      - .env
    environment:
      DEBUG: ${DEBUG:-0}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      DOCKER_HOST: unix:///var/run/docker.sock
      SKIP_SSL_CERT_DOWNLOAD: 1
      DISABLE_EVENTS: 1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./localstack/volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
